stages:
  - build
  - deploy

image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind

variables:
  APPLICATION_NAME: camera-viewer
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  only:
    - master
  tags:
    - dind
  before_script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    # Building the container image
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    # Pushing the images to the registry
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  only:
    - master
  stage: deploy
  tags:
    - dind
  before_script:
    - kubectl config use-context moreillon_ci/moreillon_k8s_home/kubernetes-agent:home
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -n ${KUBERNETES_NAMESPACE} -f -
