apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${CONTAINER_IMAGE_TAGGED}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
           name: environment-variables
        env:
          - name: VUE_APP_API_URL
            value: https://api.cameras.home.maximemoreillon.com
          - name: VUE_APP_LOGIN_URL
            value: https://api.users.maximemoreillon.com/v2/auth/login
          - name: VUE_APP_IDENTIFICATION_URL
            value: https://api.users.maximemoreillon.com/v2/users/self
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
  - port: 80
  selector:
    app: ${APPLICATION_NAME}
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - cameras.home.maximemoreillon.com
    secretName: ${APPLICATION_NAME}
  rules:
  - host: cameras.home.maximemoreillon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ${APPLICATION_NAME}
          servicePort: 80
