apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-viewer
  template:
    metadata:
      labels:
        app: camera-viewer
    spec:
      containers:
      - name: camera-viewer
        image: moreillon/camera-viewer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
           name: environment-variables
        env:
          - name: VUE_APP_API_URL
            value: https://api.cameras.home.maximemoreillon.com
---
apiVersion: v1
kind: Service
metadata:
  name: camera-viewer
spec:
  ports:
  - port: 80
  selector:
    app: camera-viewer
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: camera-viewer
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # This is necessary, no idea why
spec:
  tls:
  - hosts:
    - cameras.home.maximemoreillon.com
    secretName: camera-viewer
  rules:
  - host: cameras.home.maximemoreillon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: camera-viewer
          servicePort: 80
